### ISSUE TITLE
[High priority] cmp cookie not working on landing pages

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1078]
Hi Team,

Leads not routing to SFDC campaign added onto the end of URL with ?cmp=

**Comment by andreituicu** [comment]
@MeghnaTewari Please add more details to this issue: Please share an example flow with links, result and expected outcome.

**Comment by MeghnaTewari** [comment]
Taking an example of this page- 

https://www.moleculardevices.com/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis

When trying to assign a custom cmp ID to a landing page by appending "?cmp=xyx" to the URL, it should direct the leads to that cmp ID in the URL, rather than the default cmp ID for that LP.

https://www.moleculardevices.com/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis?cmp=70170000000hlRa

Like in the above URL, I have assigned a custom cmp id "70170000000hlRa" in the URL, so the leads should go to this campaign instead of the default. 


This scenario is working for the global RFQ. Chceck with this URL

https://www.moleculardevices.com/quote-request?cmp=7010g000000dcDT

**Comment by andreituicu** [comment]
@MeghnaTewari @dev-rajneeshkumar  the following PR https://github.com/hlxsites/moleculardevices/pull/1088 implements the flow you described above, following the same pattern as the quote request, please check it and let me know if it correct.

You can test with https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis .

I want to verify that the following corner cases are correctly handled:
1. Cookie set by another page.
if you go on any page with the query parameter `cmp` set, this will be propagated to any landing pages the user navigates to afterwards. Same as with `/qoute-request`

To give a concrete example:
If you go to  https://fix-1078--moleculardevices--hlxsites.hlx.live/quote-request?cmp=test1
And then to you go to https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis
`cmp` will be set to `test1`, even if it is not in the query string, because the first page set the cookie for it.

Is this correct?

2. Iframe url without `cmp`
If the iframe url doesn't have a `cmp` parameter set, we don't set it. We only replace it, if there is one.

Is this correct? I didn't find a landing page in this case, so may be theoretical, but want to understand the expectation.

Do you have more landing pages where I can check to see it working?

**Comment by MeghnaTewari** [comment]
> 
> Do you have more landing pages where I can check to see it working?

@andreituicu here are a few other LP 

https://www.moleculardevices.com/en/assets/ebook/dd/img/quantitate-neuron-potential
https://www.moleculardevices.com/en/assets/app-note/br/optimizing-performance-of-transcreener-fluorescence-polarization-assays-with-the-spectramax-id5-multi-mode-microplate-reader
https://www.moleculardevices.com/en/assets/scientific-posters/br/rapid-assessment-of-viability-in-patient-derived-colorectal-cancer-organoids

**Comment by MeghnaTewari** [comment]
> Are there any other pages where this should happen aside from `Landing Pages` or `Quote request`?

CMP cookie case is also applied on customer breakthrough pages on Request a quote for this setup link

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f1dcc6f8-4bb3-4300-947f-bd1849ff5dcf)
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e4c71bdd-c727-4c03-946b-4d831826ad70)

For each CB there is a separate custom cmp that is assigned on the Request a Quote URL. This is working fine on live right now.

**Comment by andreituicu** [comment]
https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/quantitate-neuron-potential

https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/app-note/br/optimizing-performance-of-transcreener-fluorescence-polarization-assays-with-the-spectramax-id5-multi-mode-microplate-reader

https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/scientific-posters/br/rapid-assessment-of-viability-in-patient-derived-colorectal-cancer-organoids

https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis 

@MeghnaTewari Thank you! these all seem to be working for me. Could you please confirm so I can merge https://github.com/hlxsites/moleculardevices/pull/1088 ?

**Comment by MeghnaTewari** [comment]
@andreituicu Yes, please merge.

**Comment by andreituicu** [comment]
Done, thank you! 👍 Applied on https://moleculardevices.com/

**Comment by dev-rajneeshkumar** [comment]
> @MeghnaTewari @dev-rajneeshkumar the following PR #1088 implements the flow you described above, following the same pattern as the quote request, please check it and let me know if it correct.
> 
> You can test with https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis .
> 
> I want to verify that the following corner cases are correctly handled:
> 
> 1. Cookie set by another page.
>    if you go on any page with the query parameter `cmp` set, this will be propagated to any landing pages the user navigates to afterwards. Same as with `/qoute-request`
> 
> To give a concrete example: If you go to https://fix-1078--moleculardevices--hlxsites.hlx.live/quote-request?cmp=test1 And then to you go to https://fix-1078--moleculardevices--hlxsites.hlx.live/en/assets/ebook/dd/img/generate-application-specific-high-content-imaging-and-analysis `cmp` will be set to `test1`, even if it is not in the query string, because the first page set the cookie for it.
> 
> Is this correct?
> 
> 2. Iframe url without `cmp`
>    If the iframe url doesn't have a `cmp` parameter set, we don't set it. We only replace it, if there is one.
> 
> Is this correct? I didn't find a landing page in this case, so may be theoretical, but want to understand the expectation.
> 
> Do you have more landing pages where I can check to see it working?

Yes @andreituicu these all cases seems good and covering all scenarios.

Thanks,
Rajneesh
