### ISSUE TITLE
Old newsletters are not working

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1089]
These are getting redirected to.pdf but showing 404 error

https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/december-2018.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/october-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/august-2021.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/november-2020.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/november-2019.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/july-2018.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/february-2020.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/january-2021.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/march-2019.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/december-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/february-2019.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/november-2021.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/november-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/august-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/may-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/march-2021.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/october-2022.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/october-2021.html
https://www.moleculardevices.com/sites/default/files/en/assets/newsletter/february-2021.html

**Comment by mhaack** [comment]
@dev-rajneeshkumar @MeghnaTewari we never go these exported, we only have the newsletters for 2023. @dev-rajneeshkumar since you have the PDF tool can you please create the PDFs. Thanks

**Comment by dev-rajneeshkumar** [comment]
@mhaack Since all newsletters are part of resources itself so all were provided in the export. Please refer to this export sheet.
![image](https://github.com/hlxsites/moleculardevices/assets/42608830/8d0f9a67-2066-425e-9f37-fba7e0377752)
https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B9984673C-96F8-469D-A5DB-7E6081BCEBA2%7D&file=franklin-all-resources-v1.xlsx&action=default&mobileredirect=true
And regarding pdf creation , we need to discuss it with Simran.

**Comment by dev-rajneeshkumar** [comment]
@mhaack  Also I think , you already imported them but just need to Publish them all. Please see exp.

https://main--moleculardevices--hlxsites.hlx.page/sites/default/files/en/assets/newsletter/november-2022.pdf

**Comment by mhaack** [comment]
This was a test I created the PDF. Yes you are right they have been all provided in the export but we did not import thema as we need the PDF version, not the HTML version.

https://adobe.sharepoint.com/sites/HelixProjects/Shared%20Documents/Forms/AllItems.aspx?ga=1&id=%2Fsites%2FHelixProjects%2FShared%20Documents%2Fsites%2Fmoleculardevices%2Fsites%2Fdefault%2Ffiles%2Fen%2Fassets%2Fnewsletter&viewid=124ad5f1%2D60ba%2D476c%2Dade8%2D7c1df274ee95 has only 2023 newsletters.

@dev-rajneeshkumar can you please create and upload the PDFs. Thanks

**Comment by dev-rajneeshkumar** [comment]
Not sure @mhaack  but I can still find more pdfs working but not exists in the same folder. So are they created earlier and then deleted? If  you are able to publish them from somewhere then please do else provide me the link. I'll do that.

https://main--moleculardevices--hlxsites.hlx.page/sites/default/files/en/assets/newsletter/december-2018.pdf
https://main--moleculardevices--hlxsites.hlx.page/sites/default/files/en/assets/newsletter/november-2019.pdf
https://main--moleculardevices--hlxsites.hlx.page/sites/default/files/en/assets/newsletter/february-2019.pdf
https://main--moleculardevices--hlxsites.hlx.page/sites/default/files/en/assets/newsletter/july-2018.pdf

Or Can you please tell me who exactly among ourselves provided these pdfs so that I can check further?

**Comment by mhaack** [comment]
> So are they created earlier and then deleted?
Yes could be because we did some testing on the resources.

I don't have these PDFs, I think @kapildhiman did.  What is the issue with just creating these and upload them. Should be quick.

**Comment by dev-rajneeshkumar** [comment]
There is no issue @mhaack but just a piece of rework for us as these were already provided.

**Comment by dev-rajneeshkumar** [comment]
Missing files has been uploaded on SharePoint now and all above mentioned newsletter links are working now.
@MeghnaTewari Please verify!

**Comment by MeghnaTewari** [comment]
Validated! All the pdfs are working now.
