### ISSUE TITLE
[HubSpot] [Thank you page] Lost 'speak to specialist' and 'demo' tracking 

### ISSUE THREAD

**Issue by lydiapuric** [hlxsites/moleculardevices#1094]
Reported by [MeghnaTewari](https://github.com/MeghnaTewari) in #1080

For TY page, for both call and demo URLs-

1. When you submit the form without clicking on this checkbox, the URL should have these parameters as well ( subscribe=false ) 

https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=false
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e4727a4a-40ba-45c5-98e7-d64590d0962d)

2. When you submit the form with the checkbox, the URL should be ( subscribe=true ) 
https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=true

I submitted the rfq for the Demo URL, please see the difference in Thank You URL

https://www.moleculardevices.com/quote-request-success?cat=3D%20Biology&cmp=70170000000hlRaAAI&rfq=Quote&subscribe=false

https://live-md30.pantheonsite.io/quote-request-success?cid=1041&rfq=Demo&subscribe=false

there is a % in between 3d biology
cmp id was not there on the old live
rfq=Demo is missing in the TY URL

Thank you URL should have pid and rfq = call/demo

As stated in https://github.com/hlxsites/moleculardevices/issues/1080#issuecomment-1686041402
This form is an embedded iframe from HubSpot. The Franklin page doesn't control the behavior.
The MolDev team has already opened discussion threads with hubspot teams.

**Comment by dev-rajneeshkumar** [comment]
@lydiapuric can you please provide a list for category pages those are missing PID?

**Comment by mhaack** [comment]
@dev-rajneeshkumar this topic is moved to an extra issue: https://github.com/hlxsites/moleculardevices/issues/1093

**Comment by dev-rajneeshkumar** [comment]
> Reported by [MeghnaTewari](https://github.com/MeghnaTewari) in #1080
> 
> For TY page, for both call and demo URLs-
> 
> 1. When you submit the form without clicking on this checkbox, the URL should have these parameters as well ( subscribe=false )
> 
> https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=false ![image](https://user-images.githubusercontent.com/138755144/261597359-e4727a4a-40ba-45c5-98e7-d64590d0962d.png)
> 
> 2. When you submit the form with the checkbox, the URL should be ( subscribe=true )
>    https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=true
> 
> I submitted the rfq for the Demo URL, please see the difference in Thank You URL
> 
> https://www.moleculardevices.com/quote-request-success?cat=3D%20Biology&cmp=70170000000hlRaAAI&rfq=Quote&subscribe=false
> 
> https://live-md30.pantheonsite.io/quote-request-success?cid=1041&rfq=Demo&subscribe=false
> 
> there is a % in between 3d biology cmp id was not there on the old live rfq=Demo is missing in the TY URL
> 
> Thank you URL should have pid and rfq = call/demo
> 
> As stated in [#1080 (comment)](https://github.com/hlxsites/moleculardevices/issues/1080#issuecomment-1686041402) This form is an embedded iframe from HubSpot. The Franklin page doesn't control the behavior. The MolDev team has already opened discussion threads with hubspot teams.

@lydiapuric  for the missing value of call/quote in thank you page url, there is no issue opened with hubspot team, But you see there is return url difference between old new website  thats why thank you page is not populating correct values. Because from husbpot side , same form is being used in old and new site as well.

Old site return url in the iframe : https://info.moleculardevices.com/rfq?product_family__c=SMax iD&product_selection__c=SMax iD&product_primary_application__c=SpectraMax iD3 and iD5 Multi-Mode Microplate Readers&return_url=https://live-md30.pantheonsite.io/quote-request-success?pid%5B219%5D%3D219&product_image=https://live-md30.pantheonsite.io/sites/default/files/styles/related_products/public/products/banners/spectramax-id5-microplate-reader..png?itok=hNWbv4Ba&website=https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers&Primary_Application_geo=SpectraMax%20iD3%20and%20iD5%20Multi-Mode%20Microplate%20Readers&cmp=70170000000hlRa&requested_qdc_discussion__c=Call

New site return url: https://info.moleculardevices.com/rfq?product_family__c=SMax+iD&product_selection__c=SpectraMax+iD3+and+iD5+Multi-Mode+Microplate+Readers&product_primary_application__c=SpectraMax+iD3+and+iD5+Multi-Mode+Microplate+Readers&cmp=7014u000001t1HqAAI%3Fcmp%3D7014u000001t1FpAAI&google_analytics_medium__c=listing&google_analytics_source__c=technet&keyword_ppc__c=&gclid__c=&product_image=NA&requested_qdc_discussion__c=Quote&return_url=https%3A%2F%2Fwww.moleculardevices.com%2Fquote-request-success%3Fcat%3DSpectraMax+iD3+and+iD5+Multi-Mode+Microplate+Readers%26cmp%3D7014u000001t1HqAAI%3Fcmp%3D7014u000001t1FpAAI

**Comment by MeghnaTewari** [comment]
@lydiapuric @mhaack reopening this issue as Thank you page issues for RFQ are still not fixed.

On submitting any request quote form on site, there are the following issues-
Example- https://www.moleculardevices.com/products/microplate-readers/multi-mode-readers/spectramax-id3-id5-readers

https://www.moleculardevices.com/quote-request-success?cat=SpectraMax%20iD3%20and%20iD5%20Multi-Mode%20Microplate%20Readers&cmp=70170000000hlRa&rfq=Quote&subscribe=false

1. There is % in between the title
2. Cmp id was not there on the old live, needs to be excluded from here as well
3. Call/demo should be present for speak to specialist and Request a demo CTA for the TY page as well

**TY page reference from old live as the same form is being used on both the places**- https://live-md30.pantheonsite.io/quote-request-success?pid[219]=219&rfq=Call&subscribe=false

**Comment by mhaack** [comment]
Looking into it.
