### ISSUE TITLE
Give access to gated resources if user is logged in https://support.moleculardevices.com/

### ISSUE THREAD

**Issue by dev-rajneeshkumar** [hlxsites/moleculardevices#1104]
If user is already logged in the support portal i.e. https://support.moleculardevices.com/ then a cookie will be created and on the basis of that value in moleculardevices.com, all gated resources will appear as ungated to that particular user.

Example cookie value: 
![image](https://github.com/hlxsites/moleculardevices/assets/42608830/b8da4db7-1402-49ef-a513-c9350a08a308)

Here are the all possible values of cookie

DISTRIBUTOR
INTEGRATOR
SALES
TECH

**Regards,
Rajneesh**

**Comment by duynguyen** [comment]
Fix is drafted in https://1104--moleculardevices--hlxsites.hlx.page/products/microplate-readers/multi-mode-readers/spectramax-i3x-readers#resources
(maybe there're other use cases on different pages)

@dev-rajneeshkumar @MeghnaTewari could you please validate the fix with all use cases?

**Comment by MeghnaTewari** [comment]
@duynguyen  Found one issue with chat URLs. 

Example - https://1104--moleculardevices--hlxsites.hlx.page/products/cellular-imaging-systems/high-content-imaging/imagexpress-confocal-ht-ai#resources
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ab976cd0-8d98-4600-982e-fe8772401314)

The brochure takes me to this page instead of the pdf - https://1104--moleculardevices--hlxsites.hlx.page/resources/brochure/imagexpress-confocal-ht-ai

adding @dev-rajneeshkumar  for discussions.

**Comment by MeghnaTewari** [comment]
@duynguyen Veirfied. This looks fine now.

**Comment by MeghnaTewari** [comment]
@duynguyen resources should be ungated in search as well when the cookie is set. I think we missed that 

https://www.moleculardevices.com/search-results#t=All&sort=relevancy&f:@md_contenttype=[Application%20Note]

**Comment by duynguyen** [comment]
@MeghnaTewari as discussed in slack gated URL in search might be tackled in #1143
