### ISSUE TITLE
Implement Coveo indexing

### ISSUE THREAD

**Issue by mhaack** [hlxsites/moleculardevices#289]
We have two options to explore:

1. a we generate the coveo.xml from our index json and store that in github repo to be picked up by coveo (this is following todays pattern)
2. we send events directly to Coveo via there Push API, either directly or via the JS SDK.

References:
* coveo sample xml see Slack https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1681752498431839
* coveo push API https://docs.coveo.com/en/68/index-content/use-the-push-api & https://docs.coveo.com/en/1546/index-content/add-or-edit-a-push-source
* coveo CLI & SDK https://github.com/coveo/push-api-client.js & https://github.com/coveo/cli
* Franklin Docs https://www.hlx.live/developer/github-actions

**Comment by jose-correia** [comment]
After fixing the index sheet, the Coveo index is working. 

The implementation followed is very straightforward since we found a way for Coveo to fetch our `query-index` sheet via Rest, and map the metadata needed. There is no need for any `coveo.xml` or github events

I added mappings for all the requested metadata including:

```
- md_country (eg: United States)
- md_lang (eg: English (US))
- md_source (eg: KB)
- md_pagetype (eg: Product)
- md_contenttype (eg: SDS)
- md_img (eg: /images/resource-icons/sds.png)
```

We can now proceed to change the source in [/blocks/coveo-search/coveo-search.js#L82](https://github.com/hlxsites/moleculardevices/blob/main/blocks/coveo-search/coveo-search.js#L82). 

Currently, the new source name is `Franklin Query Index`
