### ISSUE TITLE
Low LHS on product pages

### ISSUE THREAD

**Issue by duynguyen** [hlxsites/moleculardevices#430]
Product pages with lots of resources give bad LHS because they have to load lots of resources. We need to improve this.

**Comment by andreituicu** [comment]
Unassigned myself as I'm going on PTO.
Current fixed in place are on the linked PRs:
* Lazy load vidyard scripts: https://github.com/hlxsites/moleculardevices/pull/447
* Lazy load blocks from hidden page tabs https://github.com/hlxsites/moleculardevices/pull/441

Current still known issues causing TBT:
* `header/helpers.js` CC @jose-correia ( this is spiking on any page, being in the header)
* `blocks/applications-carousel/applications-carousel.js` CC @duynguyen 

<img width="919" alt="Screenshot 2023-06-22 at 11 45 25" src="https://github.com/hlxsites/moleculardevices/assets/3651689/9ca98fac-4c17-416c-b945-10c173855550">

**Comment by andreituicu** [comment]
there are more unattributable long tasks, which I'm not 100% sure where they are coming from, but what I've noticed is that commenting out the menu and applications carousel brings the TBT to a good level, so they might be connected, meaning fixing those could fix the Unattributables as well.

<img width="919" alt="Screenshot 2023-06-22 at 11 46 20" src="https://github.com/hlxsites/moleculardevices/assets/3651689/31c26e95-5d1d-46d7-b65a-218f8e4c1205">

**Comment by andreituicu** [comment]
Keeping this one instead, because I has more historic context. Closing https://github.com/hlxsites/moleculardevices/issues/857 instead.

**Comment by mhaack** [comment]
Closing as defered, can be re-opend if needed later.
